services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'  
    volumes:
      - ./db/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql