[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "linkage"
version = "0.0.1"
description = "A configurable record linkage algorithm"
dependencies = ["rapidfuzz==3.9.6", "fhirpathpy==1.1.1"]
